spring.application.name=student-task-system

# MSSQL Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:sqlserver://localhost:51020;databaseName=StudentTaskSystemDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate & JPA Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# E-Posta (Gmail SMTP) Canlı Gönderim Ayarları
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ogrenci.gorev.sistemi@gmail.com
spring.mail.password=vsxsbctrspklwspb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com